### ISSUE TITLE
Move over to `wasmparser` crate for v1 Wasm parsing and validation

### ISSUE THREAD

**Issue by Robbepop** [paritytech/wasmi#307]
For Wasm parsing and validation we currently use `parity_wasm` and `wasmi_validation` crates respectively.
Both crates are mature but have aged over time and have not tracked more recent Wasm developments.

For the `v1` implementation we want to settle onto the `wasmparser` crate that can handle both, parsing and validation, of Wasm efficiently and also supports all the more recent Wasm proposals and more.
Beyond this it also provides its user with more utilities and therefore allows for streaming compilation and parallel compilation.

One critical aspect of having `wasmparser` support is that it supports already standardized features such as Wasm `multivalue` which are tightly integrated into more recent versions of the Wasm spec test suite. With our current tooling around `parity_wasm` and `wasmi_validate` we would need to invest great amount of maintenance into supporting those features so that we can update onto more recent versions of the official Wasm spec testsuite.

The main problem with `wasmparser` is that it currently does not support `no_std` builds.
This is by design decision of the Wasmtime team and has no real technical reason. Indeed supporting `no_std` for `wasmparser` is quite straight forward: https://github.com/bytecodealliance/wasm-tools/pull/364

We deem it is a lot less work to maintain a `no_std` `wasmparser` fork ourselves than maintaining our own Wasm parsing and validation infrastructure.

## ToDo

- [ ] Fork `wasmparser`, add `no_std` support and publish the fork on crates.io.
    - It is extremely important that full attribution is credited to the Bytecode Alliance since it is basically their project and work.
    - If a new `wasmparser` version is released we are required to update our fork accordingly and timely.
- [ ] Use our `wasmparser` fork for `v1` module compilation and validation.
- [ ] Test that the work passes the Wasm spec test suite and basically produces the same outputs (or better) than before.
