### ISSUE TITLE
Allow for multiple `wasmi::Engine` backends

### ISSUE THREAD

**Issue by Robbepop** [paritytech/wasmi#558]
Currently `wasmi` only supports a single `Engine` to execute Wasm bytecode.

The engine that is currently in use is a simple stack machine that translates incoming Wasm bytecode into `wasmi` bytecode that is optimized for efficient execution. But still, the instruction set is modelled after a stack machine just as Wasm bytecode is.

[There is ongoing work](https://github.com/paritytech/wasmi/pull/367) to experiment with other models of execution that are based on more efficient machine types such as a register machine. However, experimentation with new engine types and comparison with the existing `wasmi` engine in use is difficult since the current `wasmi` architecture does not allow for multiple engine backends. Therefore new engines have to replace the old one.

However, different engine backends might have different advantages. Therefore having multiple different engines at hand might be very useful to certain users. Besides the classic stack machine based engine backend and the experimental register machine backend there might also be room for an engine backend specialized for debugging that can act as a timetravel debugger as well as even JIT based engine backends.

For that we need to find proper interfaces for `wasmi` that allow for this flexibility.

## Workspace Design

Currently we have `wasmi`, `wasmi_core` and `wasmi_arena` crates in the workspace.
For our purposes of allowing different `wasmi` engine backends we need to split up the big `wasmi` crate into several chunks and turn it into an umbrella crate finally.

The crates we are going to need for proper decoupling of concerns are:

- `wasmi_engine`
    - **Depends on:** `wasmparser-nostd`, `wasmi_core`, `wasmi_arena`
    - **Depended on by:** `wasmi_vm`, any `wasmi` backend crate
    - **Description:** Contains definitions common to all `wasmi` engine backends and defines engine agnostic interfaces.
    - **Exposes:** Generic `Engine<T>` where `T` is the chosen engine backend implementation as well as `EngineBackend` trait that `T` needs to satisfy.
- `wasmi_vm`
    - **Depends on:** `wasmi_engine`, `wasmi_core`, `wasmi_arena`, `wasmparser-nostd`
    - **Depended on by:** `wasmi`, any `wasmi` backend crate
    - **Description:** Contains common Wasm definitions such as `Store`, `Memory`, `Table`, `Global`, `Func`, `Module`, `Instance` etc. Basically this defines most of what today's `wasmi` crate does.
    - **Exposes:** An API similar to today's `wasmi` crate without the UX specific parts.
- `wasmi_stackmachine`
    - **Depends on:** `wasmi_engine`, `wasmi_vm`, `wasmi_core`, `wasmi_arena`
    - **Depended on by:** `wasmi` (for its default engine feature)
    - **Description:** Contains the definitions specific to the current `wasmi` engine implementation.
    - **Exposes:** A single type `StackMachine` that can be used as parameter for the generic `wasmi_engine::Engine<T>`.
- `wasmi_regmachine`
    - **Depends on:** `wasmi_engine`, `wasmi_vm`, `wasmi_core`, `wasmi_arena`
    - **Depended on by:** Users of `wasmi`.
    - **Description:** Contains the definitions specific to the experimental register machine `wasmi` engine backend.
    - **Exposes:** A single type `RegisterMachine` that can be used as parameter for the generic `wasmi_engine::Engine<T>`.
- `wasmi`
    - **Depends on:** `wasmi_vm`, `wasmi_core`, `wasmi_stackmachine` (optionally)
    - **Depended on by:** Users of `wasmi`.
    - **Description:** Umbrella crate that does not define anything by itself but depends on different `wasmi` workspace crates to expose a common user friendly API to the outside world. This is the crate which users of `wasmi` will depend on.
    - **Exposes:** An API similar to today's `wasmi` crate with additional default engine crate feature.

## ToDo List (in order)

- [ ] Create the `wasmi_engine` crate. Make `wasmi` crate depend on it.
    - At this point the `wasmi` stack machine engine backend still resides within the `wasmi` crate itself.
    - Engine agnostic and common engine definitions no longer are defined within the `wasmi` after after this point.
- [ ] Rename the `wasmi` crate to `wasmi_vm` and create the new `wasmi` umbrella crate that simply reexports `wasmi_vm` mostly.
- [ ] Create the `wasmi_stackmachine` crate. Introduce `default-engine` default crate feature to `wasmi` umbrella crate.
    - After this task the `wasmi_vm` crate no longer contains any engine backend implementation.
- [ ] Create the `wasmi_regmachine` crate based on https://github.com/paritytech/wasmi/pull/367.
    - After this task we can finally merge the register machine implementation PR for experimentation purposes.

![2022-11-20-110942_1639x1360_scrot](https://user-images.githubusercontent.com/8193155/202896360-cd0fe191-1426-4983-85b0-ff9fe06d7cf7.png)

**Comment by Robbepop** [comment]
This issue is already quite old and many things have changed and knowledge was gained since then.

The learnings are that it oftentimes is possible to have a single engine support multiple different use cases efficiently with the right dose of creativity. One example of this is the fuel metering support built-into `wasmi` where fuel is charged in blocks that are determined during translation phase so that the overhead during execution of the Wasm blob is very minimal.

Another future use case is debuggability. Maybe we can approach this topic in a similar vein but that has to be done via research in the future.

I personally no longer believe in a multi-`Engine` future for `wasmi`. The biggest reason for this is the maintenance overhead required to maintain multiple different `Engine` backends with their multitudes of intricacies. Therefore it is much better to have a single well-engineered `Engine` backend to rule them all and put a lot of effort into.

There I close this issue now. We might re-open and re-investigate this issue in the future again, though.
