### ISSUE TITLE
Add `ResourceLimiter` to `wasmi::Store`

### ISSUE THREAD

**Issue by Robbepop** [paritytech/wasmi#728]
As requested in [this comment](https://github.com/paritytech/wasmi/issues/720#issuecomment-1565809927) some `wasmi` users could profit from having access to a Wasmtime style [`ResourceLimiter` API](https://docs.rs/wasmtime/9.0.2/wasmtime/trait.ResourceLimiter.html).

Since `wasmi` tries to mirror the Wasmtime API we should and could mirror this API from Wasmtime as well. I think it would be a nice addition, however, special care has to be taken that translation and execution performance do not regress.

## TODOs

- [ ] Implementation
    - [ ] Implement the `ResourceLimiter` trait in `wasmi`.
    - [ ] Implement [`Store::limiter` API](https://docs.rs/wasmtime/9.0.2/wasmtime/struct.Store.html#method.limiter).
    - [ ] Implement [`StoreLimits` type](https://docs.rs/wasmtime/10.0.1/wasmtime/struct.StoreLimits.html) implementing `StoreLimiter` trait as convenience for users.
    - [ ] Implement [`StoreLimitsBuilder` type](https://docs.rs/wasmtime/10.0.1/wasmtime/struct.StoreLimitsBuilder.html) as convenience for constructing `StoreLimits`.
- [ ] Testing & QA
    - [ ] Add tests to verify that the implemented functionality works as intended.
    - [ ] Add proper docs to the feature as well as some doc example.
    - [ ] Validate with benchmarks that using this feature does not disrupt `wasmi` performance too much.
    - [ ] Validate with benchmarks that _not_ using this feature does not disrupt `wasmi` performance significantly.

**Note:** Wasmtime's [`epoch_interruption`](https://docs.rs/wasmtime/9.0.2/wasmtime/struct.Config.html#method.epoch_interruption) is not needed since `wasmi` does not (yet) support `async` execution.

**Comment by Robbepop** [comment]
Sorry for my late response!

At the moment I am working on https://github.com/paritytech/wasmi/pull/729 which takes a big chunk of my time. I thought that this issue might be a perfect candidate for external contributions since it should be a rather local change. If it is extremely pressing we can probably work something out together. Shouldn't be a big task from what I see so far.

**Comment by graydon** [comment]
@Robbepop ok if you're comfortable having us implement this, we're happy to direct our efforts to it. It looks like it ought to be relatively straightforward.

**Comment by Robbepop** [comment]
@graydon Yes I am very comfortable with this being contributed externally. From the top of my head this should be fairly straight forward to implement. The worst thing that could happen is that we have to figure out performance issues reported by the CI.
